### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [tterev3/dash-cam-controller#1]
Hello!

I found link to this project from https://hackaday.com/2020/09/25/hacking-a-cheap-action-cam-into-a-dashcam-with-a-microcontroller/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by tterev3** [comment]
License added, thank you for the reminder

**Comment by vazhnov** [comment]
@tterev3 , thank you for fast answer and for the MIT license!
